### PR TITLE
FH-3118 Add afterAll test to syncSpec

### PR DESCRIPTION
**Pull request by aidenkeating**
Currently four records are created in the MongoDB collections for
the tests. These are now deleted when all tests end.

### CODE REVIEW

**Comment by aidenkeating** [comment]
Oops. Forgot that Travis is integrated now!

**Comment by aidenkeating** [comment]
Much better. @danbev Would you mind taking a look?

**Review by danbev — APPROVED** [review]

**Comment by danbev** [comment]
LGTM 👍

**Comment by danbev** [comment]
Landed in 29bbb000604437ffe24de4a97c7930daa491df59

**Pull request closed without merging**
